@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title 启动相关任务清单

* <&flag>application
** DefaultConfig
*** isync_config表的租户都不对，似乎没用
** ContentCache
***:<code>
GlobalEventExecFactory
   implements
Thread.UncaughtExceptionHandler
</code>
;

** DictItemInitCache
*** 从isync.ISYNC_DIC_MAP_ITEM构建缓存
** GroupInitCache
***:<code>
  executeGroupCache(ServiceConstant.HIS)
  executeGroupCache(ServiceConstant.WHIS)
</code>;
** RecordMapInitCache
** JobBase
***:<code>
//a、b环境
Object o = redisOperation.get(RedisKey.getEnvironment())
if (o==null || o.toString().isEmpty()){
    redisOperation.set(RedisKey.getEnvironment(), ServiceConstant.ENVIRONMENT_A)
}
</code>
;
** 6.JobAutoOld2NewProcessor
***:<code>
 if (isUseCluster){
    return
}
old2newExecutor.schedule(() -> this.asyncProcess(),
    triggerContext -> new CronTrigger("0/20 * * * * ?").nextExecutionTime(triggerContext))

;
** 6.jobFailedAutoOld2NewProcessor
** 7.JobFailedNew2OldProcessor
***:<code>
public void process(){
        if (isUseCluster){
            return
        }
        new2oldExecutor.schedule(() -> this.asyncProcess(),
                triggerContext -> new CronTrigger("0/5 * * * * ?").nextExecutionTime(triggerContext))
    }
</code>;
** 8.JobFailedOld2NewProcessor

** 9.JobNew2OldProcessor
** 10.jobOld2NewProcessor

** SmSaapServiceImpl

*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap
