@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title My super title

* <&flag>application
** ContentCache
** DefaultConfig
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** DictItemInitCache
** GroupInitCache
** JobBase
** JobAutoOld2NewProcessor
** JobFailedNew2OldProcessor
** JobFailedOld2NewProcessor
** jobFailedAutoOld2NewProcessor
** JobNew2OldProcessor
** jobOld2NewProcessor
** RecordMapInitCache
** SmSaapServiceImpl

*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap
